const menuData = {
    pizza: [
      {
        id: 1,
        name: "مخصوص سرو",
        description: "فیله مرغ،فیله گوسفند،ژامبون گوشت",
        pictureUrl: require("../../assets/starters/img1.png"),
        price: "195000295000",
      },
      {
        id: 2,
        name: "استیک",
        description: "گوشت استیک مزه دار شده",
        pictureUrl: require("../../assets/starters/img2.png"),
        price: "240000340000",
      },
      {
        id: 3,
        name: "کنیباله",
        description: "گوشت چرخ کرده",
        pictureUrl: require("../../assets/starters/img3.png"),
        price: "195000295000",
      },
      {
        id: 4,
        name: "پنیر&رست بیف",
        description: "گوشت ریش ریش شده",
        pictureUrl: require("../../assets/starters/img2.png"),
        price: "220000320000",
      },
      {
        id: 5,
        name: "نیویورک",
        description: "بیکن گوساله،گوشت چرخ کرده",
        pictureUrl: require("../../assets/starters/img3.png"),
        price: "",
      },
      {
        id: 6,
        name: "چیکن گریل",
        description: "فیله مرغ طعم دار شده",
        pictureUrl: require("../../assets/starters/img2.png"),
        price: "185000295000",
      },
      {
        id: 7,
        name: "کاپری",
        description: "%ژامبون گوسن مرغ 10",
        pictureUrl: require("../../assets/starters/img3.png"),
        price: "148000248000",
      },
      {
        id: 8,
        name: "پستو",
        description: "فیله مرغ،پپرونی",
        pictureUrl: require("../../assets/starters/img2.png"),
        price: "195000298000",
      },
      {
        id: 9,
        name: "وجی تری",
        description: "سبزیجات",
        pictureUrl: require("../../assets/starters/img3.png"),
        price: "195000298000",
      },
    ],
  
    fried: [
      {
        id: 1,
        name: "سینه مرغ سوخاری",
        description: "",
        pictureUrl: require("../../assets/breakfast/img1.png"),
        price: "170000",
      },
      {
        id: 2,
        name: "فیله مرغ سوخاری",
        description: "",
        pictureUrl: require("../../assets/breakfast/img2.png"),
        price: "175000",
      },
      {
        id: 3,
        name: "قارچ سوخاری",
        description: "",
        pictureUrl: require("../../assets/breakfast/img3.png"),
        price: "85000",
      },
    ],
  
    hot_dog: [
      {
        id: 1,
        name: "هات داگ تنوری",
        description: "",
        pictureUrl: require("../../assets/dinner/img1.png"),
        price: "160000",
      },
      {
        id: 2,
        name: "رست بیف تنوری",
        description: "",
        pictureUrl: require("../../assets/dinner/img2.png"),
        price: "220000",
      },
      {
        id: 3,
        name: "برگر تنوری",
        description: "",
        pictureUrl: require("../../assets/dinner/img3.png"),
        price: "215000",
      },
      {
        id: 4,
        name: "ژامبون تنوری",
        description: "",
        pictureUrl: require("../../assets/dinner/img4.png"),
        price: "160000",
      },
      {
        id: 5,
        name: "چیکن تنوری",
        description: "",
        pictureUrl: require("../../assets/drinks/img1.png"),
        price: "1700000",
      },
      {
        id: 6,
        name: "هات داگ",
        description: "",
        pictureUrl: require("../../assets/drinks/img2.png"),
        price: "1900000",
      },
      {
        id: 7,
        name: "میکس تنوری",
        description: "",
        pictureUrl: require("../../assets/drinks/img3.png"),
        price: "190000",
      },
  {
        id: 8,
        name: "هات بیف",
        description: "",
        pictureUrl: require("../../assets/drinks/img3.png"),
        price: "196000",
      },
    ],
  
  
   feed: [
      {
        id: 1,
        name: "استیک مرغ",
        description: "",
        pictureUrl: require("../../assets/drinks/img1.png"),
        price: "145000",
      },
      {
        id: 2,
        name: "فیله",
        description: "",
        pictureUrl: require("../../assets/drinks/img2.png"),
        price: "145000",
      },
      {
        id: 3,
        name: "برگر",
        description: "",
        pictureUrl: require("../../assets/drinks/img3.png"),
        price: "145000",
      },
     {
        id: 4,
        name: "میکس",
        description: "استیک مرغ و برگر",
        pictureUrl: require("../../assets/drinks/img3.png"),
        price: "150000",
      },
    ],
  
   burgers: [
      {
        id: 1,
        name: "برگرمخصوص",
        description: "",
        pictureUrl: require("../../assets/drinks/img1.png"),
        price: "120000",
      },
      {
        id: 2,
        name: "چیزبرگر",
        description: "",
        pictureUrl: require("../../assets/drinks/img2.png"),
        price: "135000",
      },
      {
        id: 3,
        name: "ماشروم برگر",
        description: "",
        pictureUrl: require("../../assets/drinks/img3.png"),
        price: "145000",
      },
      {
        id: 4,
        name: "دوبل برگر",
        description: "",
        pictureUrl: require("../../assets/drinks/img3.png"),
        price: "185000",
      },
      {
        id: 5,
        name: "رویال برگر",
        description: "",
        pictureUrl: require("../../assets/drinks/img3.png"),
        price: "150000",
      },
      {
        id: 6,
        name: "سوپر ساندویچ",
        description: "",
        pictureUrl: require("../../assets/drinks/img3.png"),
        price: "189000",
      },
      {
        id: 7,
        name: "همبر معمولی",
        description: "",
        pictureUrl: require("../../assets/drinks/img3.png"),
        price: "69000",
      },
    ],
  
   sandwiches: [
      {
        id: 1,
        name: "%ژامبون گوشت90",
        description: "",
        pictureUrl: require("../../assets/drinks/img1.png"),
        price: "120000",
      },
      {
        id: 2,
        name: "%ژامبون مرغ 90",
        description: "",
        pictureUrl: require("../../assets/drinks/img2.png"),
        price: "110000",
      },
      {
        id: 3,
        name: "فیله مرغ کبابی",
        description: "",
        pictureUrl: require("../../assets/drinks/img3.png"),
        price: "175000",
      },
      {
        id: 4,
        name: "رست بیف",
        description: "",
        pictureUrl: require("../../assets/drinks/img3.png"),
        price: "200000",
      },
      {
        id: 5,
        name: "کوکتل",
        description: "",
        pictureUrl: require("../../assets/drinks/img3.png"),
        price: "95000",
      },
    ],
  
   snacks: [
      {
        id: 1,
        name: "بسیب زمینی سرخ کرده",
        description: "",
        pictureUrl: require("../../assets/drinks/img1.png"),
        price: "50000",
      },
      {
        id: 2,
        name: "سیب زمینی تنوری",
        description: "",
        pictureUrl: require("../../assets/drinks/img2.png"),
        price: "65000",
      },
      {
        id: 3,
        name: "نان سیر",
        description: "",
        pictureUrl: require("../../assets/drinks/img3.png"),
        price: "95000",
      },
     
    ],
  
  
   salad: [
      {
        id: 1,
        name: "سالاد سزار با فیله",
        description: "",
        pictureUrl: require("../../assets/drinks/img1.png"),
        price: "130000",
      },
      {
        id: 2,
        name: "سوخاری",
        description: "",
        pictureUrl: require("../../assets/drinks/img2.png"),
        price: "130000",
      },
      {
        id: 3,
        name: "سالاد فصل",
        description: "",
        pictureUrl: require("../../assets/drinks/img3.png"),
        price: "50000",
      },
    ],
  
  persian_food: [
      {
        id: 1,
        name: "چلوکباب سلطانی",
        description: "چلوایرانی،برگ راسته گوسفندی،کوبیده گوسفندی",
        pictureUrl: require("../../assets/drinks/img1.png"),
        price: "320000",
      },
      {
        id: 2,
        name: "چلوکباب برگ",
        description: "چلوایرانی،راسته گوسفندی",
        pictureUrl: require("../../assets/drinks/img2.png"),
        price: "280000",
      },
      {
        id: 3,
        name: "چلو جوجه زعفرانی",
        description: "چلو ایرانی",
        pictureUrl: require("../../assets/drinks/img3.png"),
        price: "210000",
      },
      {
        id: 4,
        name: "چلو کباب کوبیده زعفرانی",
        description: "چلو ایرانی،کوبیده گوسفندی",
        pictureUrl: require("../../assets/drinks/img3.png"),
        price: "195000",
      },
      {
        id: 5,
        name: "چلوجوجه لاری",
        description: "چلو ایرانی",
        pictureUrl: require("../../assets/drinks/img3.png"),
        price: "230000",
      },
      {
        id: 6,
        name: "چلوکباب درباری",
        description: "چلوایرانی،استیک مرغ،تک سیخ کوبیده گوسفندی",
        pictureUrl: require("../../assets/drinks/img3.png"),
        price: "265000",
      },
      {
        id: 7,
        name: "چلوکباب نگینی",
        description: "چلوایرانی،کوبیده گوسفندی،استیک مرغ نگینی",
        pictureUrl: require("../../assets/drinks/img3.png"),
        price: "230000",
      },
      {
        id: 8,
        name: "چلوکباب بناب",
        description: "چلوایرانی،کوبیده گوسفندی،گردو،سبزیجات معطر",
        pictureUrl: require("../../assets/drinks/img3.png"),
        price: "240000",
      },
      {
        id: 9,
        name: "چلوکباب بختیاری",
        description: "چلوایرانی،استیک مرغ،راسته گوسفندی،فلفل کبابی",
        pictureUrl: require("../../assets/drinks/img3.png"),
        price: "220000",
      },
      {
        id: 10,
        name: "چلوجوجه با استخوان",
        description: "چلو ایرانی",
        pictureUrl: require("../../assets/drinks/img3.png"),
        price: "235000",
      },
      {
        id: 1,
        name: "زرشک پلو با مرغ",
        description: "چلوایرانی،ران مرغ،سس مخصوص",
        pictureUrl: require("../../assets/drinks/img1.png"),
        price: "165000",
      },
      {
        id: 2,
        name: "اکر جوجه با چلو",
        description: "چلو ایرانی،نصف مرغ با سس مخصوص،رب انار",
        pictureUrl: require("../../assets/drinks/img2.png"),
        price: "195000",
      },
      {
        id: 3,
        name: "کاسه کباب با چلو 2 نفره",
        description: "دو پرس چلوایرانی،گنچه گوسفندی،جوجه کباب،کوبیده گوسفندی،فلفل قلمی،قارچ،کنجد،کره گوسفندی،",
        pictureUrl: require("../../assets/drinks/img3.png"),
        price: "520000",
      },
   {
        id: 4,
        name: "دیزی",
        description: "نخود،لوبیا،گوشت گوسفندی،سیب زمینی،گوجه،دنبه گوسفندی،",
        pictureUrl: require("../../assets/drinks/img3.png"),
        price: "",
      },
      {
        id: 5,
        name: "چلو کنجه",
        description: "چلو ایرانی",
        pictureUrl: require("../../assets/drinks/img3.png"),
        price: "265000",
      },
      {
        id: 6,
        name: "چلو ساده ایرانی",
        description: "",
        pictureUrl: require("../../assets/drinks/img3.png"),
        price: "60000",
      }
    ],
  
  };
  
  export default menuData;
  